import './global.css';
import { UiLayout } from '../components/ui/ui-layout';
import { ClusterProvider } from '../components/cluster/cluster-data-access';
import { SolanaProvider } from '../components/solana/solana-provider';
import { ReactQueryProvider } from './react-query-provider';

export const metadata = {
  title: 'complete-bd',
  description: 'Generated by create-solana-dapp',
};

const links: { label: string; path: string }[] = [
  { label: 'Log in', path: '/login' },
  { label: 'Services', path: '/services' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="flex flex-col min-h-screen h-full">
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <UiLayout links={links} />
              <div className="flex-grow">
                {children}
              </div>
              <footer className="bg-slate-900 text-neutral-content p-4">
                <div className="container mx-auto text-center">
                  © 2024 BlockLab. All rights reserved.
                </div>
              </footer>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
